#!/usr/bin/env node

import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "../../../scripts/runtime-builder.mjs";

const childBridgeSource = "src/child-communication-bridge.ts";

export const { buildRuntime, validateEagerGraph, validateGeneratedFiles, publishRuntime } = createRuntimeBuilder({
  packageRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  temporaryPrefix: ".pi-subagents",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- generated entries use .ts extensions for Pi's Jiti loader.",
  ].join("\n"),
  entries: { index: "src/index.ts", "child-communication-bridge": childBridgeSource },
  validateGraph({ allInputs, eagerInputs, eagerOutputs, entryPaths }) {
    for (const input of allInputs) {
      if (!input.startsWith("/src/")) throw new Error(`Bundled non-package source: ${input}`);
    }
    if ([...eagerInputs].some((input) => input.endsWith(`/${childBridgeSource}`))) {
      throw new Error(`Child-process entry is eager: ${childBridgeSource}`);
    }
    if (eagerOutputs.has(entryPaths["child-communication-bridge"])) {
      throw new Error("Child-process entry is reachable from the main extension entry");
    }
  },
  async validateFiles({ outputDirectory }) {
    const mainSource = await readFile(join(outputDirectory, "index.ts"), "utf8");
    if (!mainSource.includes('"./child-communication-bridge.ts"')) {
      throw new Error("Generated main entry does not reference the generated child bridge");
    }
  },
});

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
