#!/usr/bin/env node

import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "../../../scripts/runtime-builder.mjs";

const forbiddenEagerInputs = [
  "src/sync/setup-switch.ts",
  "src/sync/sync-operations.ts",
  "src/sync/sync-queries.ts",
  "src/sync/sync-inspection.ts",
  "src/sync/sync-mutations.ts",
  "src/ui/manager-ui.ts",
  "src/ui/setup/setup-wizard.ts",
  "src/ui/setup/setup-switcher.ts",
  "src/ui/setup/setup-actions.ts",
  "src/ui/setup/s3-ui.ts",
  "src/ui/setup/setup-location-ui.ts",
  "src/ui/manager-result-dispatcher.ts",
  "src/ui/file-selection.ts",
  "src/ui/remote-selection-ui.ts",
  "src/backends/s3/s3-backend.ts",
  "src/backends/webdav/webdav-backend.ts",
  "src/backends/git/git-backend.ts",
];

export const { buildRuntime, validateEagerGraph, validateGeneratedFiles, publishRuntime } = createRuntimeBuilder({
  packageRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  temporaryPrefix: ".pi-sync",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- generated JavaScript uses a .ts extension for Pi's Jiti loader.",
  ].join("\n"),
  forbiddenEagerInputs,
  forbiddenEagerExternals: ["@narumitw/pi-tui-kit", "fast-xml-parser"],
  includeDynamicExternals: true,
  validateGraph({ allInputs }) {
    for (const input of forbiddenEagerInputs) {
      if (!allInputs.has(`/${input}`))
        throw new Error(`First-use implementation is missing from build inputs: ${input}`);
    }
  },
});

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
