#!/usr/bin/env node

import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "../../../scripts/runtime-builder.mjs";

export const { buildRuntime, validateEagerGraph, validateGeneratedFiles, publishRuntime } = createRuntimeBuilder({
  packageRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  temporaryPrefix: ".pi-starship",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- the generated entry uses a .ts extension for Pi's Jiti loader.",
  ].join("\n"),
  forbiddenEagerInputs: [
    "src/commands.ts",
    "src/command-inspector.ts",
    "src/command-preset-picker.ts",
    "src/command-preview.ts",
    "src/presets/catalog.ts",
    "src/runtime/cloud.ts",
    "src/runtime/deployment.ts",
    "src/runtime/development.ts",
    "src/runtime/execution.ts",
    "src/runtime/languages.ts",
    "src/runtime/package.ts",
  ],
  forbiddenEagerExternals: ["@narumitw/pi-tui-kit", "yaml"],
  matchExternalSubpaths: false,
  includeDynamicExternals: true,
  async validateFiles({ outputDirectory, runtimeFiles }) {
    for (const runtimePath of runtimeFiles) {
      const source = await readFile(join(outputDirectory, runtimePath), "utf8");
      // Compiled Pi resolves call-time packages against its embedded graph, not the install root.
      // esbuild renames the returned require binding, so check the factory call instead.
      if (/\bcreateRequire\s*\(/u.test(source)) {
        throw new Error(`Generated runtime resolves a package at call time in ${runtimePath}`);
      }
    }
  },
});

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
